services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 14231423
      POSTGRES_DB: construction
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"

  api:
    build:
      context: ./app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:14231423@db:5432/construction?sslmode=disable
      JWT_SECRET: supersecretkey
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5055:80"
    depends_on:
      - db
